---
title: "project2"
author: "Jialin Sun, yiming lei, Yilin Liang, Ruilin Ma, Rachit Rakesh Khade"
date: "2021/7/23"
output:
  pdf_document:
    latex_engine: pdflatex
    number_sections: yes
  html_document:
    df_print: paged
  word_document: default
fig_caption: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(eval = TRUE, warning = FALSE, message = FALSE, comment = NA)
```

```{r libraries,echo = FALSE}
library(tidyverse)
library(moderndive)
library(skimr)
library(kableExtra)
library(gridExtra)
library(devtools)
library(magrittr)
library(ggplot2)
library(maps)
library(RColorBrewer)
library(viridis)
library(ggpubr)
library(GGally)
library(corrplot)
library(knitr)
library(olsrr)
library(data.table)
library(moderndive)
library(ggfortify)
library(diagram)
library(ggthemes)
library(cowplot)
library(showtext)
library(ggnewscale)
library(gapminder)
library(janitor)
```

```{R data, echo = FALSE, eval = TRUE, warning = FALSE, message = FALSE}
#read the file
dat<-read.csv("dataset9.csv")
#add the score column,if rating>7,then 1,else 0
dat<-mutate(dat,score=ifelse(rating>7,1,0))
#replace NA with mean value in length column 
dat$length[is.na(dat$length)]<-mean(dat$length,na.rm = TRUE)
dat$scorename[dat$score==1] <- "greater than 7"
dat$scorename[dat$score==0] <- "lower than 7"
```

